Fix LCL scaling of non-default fonts. Taken from Laz-VTV r63830+63831
blikblum/VirtualTreeView-Lazarus pull request #25
Opened 2021-05-05 17:48 UTC by wp-xyz

My changes in the Lazarus VTV to be included in your repo. It fixes LCL scaling of fonts having changed properties.

2021-05-06 16:38 UTC, blikblum requested changes

2021-05-06 16:38 UTC, blikblum commented on Source/VirtualTrees.pas
> +    procedure AutoAdjustLayout(const AXProportion, AYProportion: Double); virtual;
Is necessary to add virtual keyword here?

Seems not related to current issue

2021-05-06 22:28 UTC, wp-xyz commented on Source/VirtualTrees.pas
> +    procedure AutoAdjustLayout(const AXProportion, AYProportion: Double); virtual;
Not necessarily. But when somebody writes a descendant of TVTHeader which has scaling-sensitive parameters they could be scaled correctly simply by overriding this virtual method.

2021-05-07 00:14 UTC, merged

2021-05-07 00:14 UTC, blikblum commented on Source/VirtualTrees.pas
> +    procedure AutoAdjustLayout(const AXProportion, AYProportion: Double); virtual;
Ok